### PR TITLE
Open drive rendering

### PR DESCRIPTION
**Pull request by AlirezaMorsali**

### CODE REVIEW

**Comment by adscib** [comment]
Can you rearrange the imports and definitions so that this script runs even if carla isn't installed? It seems like the script doesn't actually use anything imported from carla.

**Comment by AlirezaMorsali** [comment]
> Can you rearrange the imports and definitions so that this script runs even if carla isn't installed? It seems like the script doesn't actually use anything imported from carla.

Done.

**Comment by adscib** [comment]
Cool. Is it possible to control the resolution of the produced gif?

**Comment by AlirezaMorsali** [comment]
o

> Cool. Is it possible to control the resolution of the produced gif?

Done.

**Comment by adscib** [comment]
```
Traceback (most recent call last):
  File "/home/ascibior/repos/invertedai/examples/carla/demo_open_drive.py", line 68, in <module>
    scene_plotter = iai.utils.ScenePlotter(
TypeError: ScenePlotter.__init__() got an unexpected keyword argument 'dpi'
```

incomplete commit?

**Comment by AlirezaMorsali** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/ascibior/repos/invertedai/examples/carla/demo_open_drive.py", line 68, in <module>
>     scene_plotter = iai.utils.ScenePlotter(
> TypeError: ScenePlotter.__init__() got an unexpected keyword argument 'dpi'
> ```
> 
> incomplete commit?

I had to change the utils.py in the package to update the sceneplotter. I assume the installed invertedai from pypi is being accessed which does not have dpi and resolution in the sceneplotter.

**Review by adscib — APPROVED** [review]

**Pull request merged**
