### PR TITLE
Develop to master

### PR DESCRIPTION
**Pull request by rf-ivtdai**

### CODE REVIEW

**Comment by Ruishenl** [comment]
@KieranRatcliffeInvertedAI  If the large area drive is ready let's make a release

**Comment by KieranRatcliffeInvertedAI** [comment]
Large initialize and large drive still need to be refactored to include AgentProperties.

**Comment by KieranRatcliffeInvertedAI** [comment]
What's the schedule release for 0.0.18? I can accelerate this if you'd like to push ASAP.

**Comment by rf-ivtdai** [comment]
We have some in-house demand right now. They need to run large_drive & large_initialize on Compute Canada machines, which has been cumbersome without an official release.

**Review by Ruishenl — APPROVED** [review]

**Pull request merged**
